        # COPY PASTE THE FOLLOWING METHODS INTO REPORT CONTROLLER AND YOU CAN DEBUG WHICH ONE MIGHT BE CAUSING A PROBLEM -------------------------------------------------
        report.zip_to_avg_home(city_state)
        report.number_payments()
        report.home_insurance(city_state)
        report.mortgage_rate()
        report.property_tax(city_state)
        report.pmi()
        report.true_monthly(city_state)
        report.monthly_principal()
        report.percentage_saved_based_on_principal()
        report.downpayment_savings_goal_end_date(10)
        report.principal_based_on_rent()
        report.downpayment_goal_monthly_savings(10)
        report.calc_downpayment_cash_value()
